name: Build project with Maven
on:
  pull_request:
  push:
    branches-ignore: [master]
  schedule:
  - cron: '2 2 * * 1-5' # run nightly master builds on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra:2
        ports:
        - 9042:9042

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Java setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Maven
      run: |-
        mvn -B clean install com.mycila:license-maven-plugin:check
